// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using projeto.ContextDB;

#nullable disable

namespace projeto.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20230605130030_criacao_banco_data_seed")]
    partial class criacao_banco_data_seed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("projeto.Models.Curso", b =>
                {
                    b.Property<int>("CursoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CursoID"));

                    b.Property<string>("Ementa")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProfessorID")
                        .HasColumnType("int");

                    b.HasKey("CursoID");

                    b.HasIndex("ProfessorID");

                    b.ToTable("Curso", (string)null);

                    b.HasData(
                        new
                        {
                            CursoID = 1,
                            Ementa = "Ementa 1",
                            Nome = "Curso 1",
                            ProfessorID = 1
                        },
                        new
                        {
                            CursoID = 2,
                            Ementa = "Ementa 1",
                            Nome = "Curso 2",
                            ProfessorID = 2
                        });
                });

            modelBuilder.Entity("projeto.Models.Professor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Complemento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UF")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.HasKey("ID");

                    b.ToTable("Professor", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Bairro = "Bairro 1",
                            Cidade = "Cidade 1",
                            Complemento = "Complemento 1",
                            Cpf = "11111111111",
                            Logradouro = "Logradouro 1",
                            Nome = "Professor 1",
                            Numero = "1",
                            Pais = "Pais 1",
                            UF = "PE"
                        },
                        new
                        {
                            ID = 2,
                            Bairro = "Bairro 2",
                            Cidade = "Cidade 2",
                            Complemento = "Complemento 2",
                            Cpf = "22222222222",
                            Logradouro = "Logradouro 2",
                            Nome = "Professor 2",
                            Numero = "2",
                            Pais = "Pais 2",
                            UF = "BA"
                        });
                });

            modelBuilder.Entity("projeto.Models.Curso", b =>
                {
                    b.HasOne("projeto.Models.Professor", "Professor")
                        .WithMany("Cursos")
                        .HasForeignKey("ProfessorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("projeto.Models.Professor", b =>
                {
                    b.Navigation("Cursos");
                });
#pragma warning restore 612, 618
        }
    }
}
